// PARA IMPORTAR FUNCIONES DE OTRAS HOJAS
import hello from "./08-2-modulos.js";
// AQUI PARA QUE DETECTE LA FUNCION DEBEMOS ASIGNAR EL VALOR DE LA EXTENSION EN ESTE CASO .JS YA QUE NO LO PONE

hello();